# Template for running the docker-socat minion in debug mode.
# Always pull the latest image from Docker Hub.
kind: ReplicationController
apiVersion: v1
metadata: 
  name: docker-socat-minion-controller-v1
  namespace: default
  labels: 
    k8s-app: docker-socat
    version: v1
spec: 
  replicas: 1
  selector: 
    k8s-app: docker-socat
    docker-socat-mode: minion
    version: v1
  template: 
    metadata: 
      labels: 
        k8s-app: docker-socat
        docker-socat-mode: minion
        version: v1
    spec: 
      volumes: 
        - 
          name: docker-unix-socket
          hostPath: 
            path: /var/run/docker.sock
      containers: 
        - 
          # The docker-socat minion responds to requests on port 4243.
          name: docker-socat
          # Change the tag to the latest released image.
          image: kubernetes/docker-socat:2015-07-01
          # Do not change the image pull policy to "Always" because Docker Hub
          # may not be able to respond in time.
          imagePullPolicy: IfNotPresent
          ports: 
            - 
              name: http-docker
              containerPort: 4243
              hostPort: 4243
              protocol: TCP
          env: 
            - 
              name: DOCKER_SOCAT_MODE
              value: minion
          volumeMounts: 
            - 
              name: docker-unix-socket
              readOnly: true
              mountPath: /var/run/docker.sock
