# Template file for docker-relay master in production mode.
# Always pull the latest binary from Docker Hub.
# Always run the master in production mode.
# Expose the master only as a service.
# See docker-relay-master-controller-debug.yaml for running the
# docker-relay master in debug mode.
kind: ReplicationController
apiVersion: v1
metadata: 
  name: docker-relay-master-controller-v1
  namespace: default
  labels: 
    k8s-app: docker-relay
    version: v1
spec: 
  replicas: 1
  selector: 
    k8s-app: docker-relay
    docker-relay-mode: master
    version: v1
  template: 
    metadata: 
      labels: 
        k8s-app: docker-relay
        docker-relay-mode: master
        version: v1
    spec: 
      containers: 
        - 
          name: docker-relay
          # Change the tag to the latest released image.
          image: kubernetes/docker-relay:2015-09-01
          # Do not change the image pull policy to "Always" because Docker Hub
          # may not be able to respond in time.
          imagePullPolicy: IfNotPresent
          ports: 
            - 
              name: docker-relay
              containerPort: 5555
              protocol: TCP
          env: 
            - 
              name: DOCKER_RELAY_MODE
              value: master
