# Template file for docker-relay master in debug mode.
# Pull the binary from Docker Hub only if it missing on the local machine.
# Always run the master in debug mode.
# Expose the master as a service and also on local port 5555.
# See docker-relay-master-controller.yaml for running the
# docker-relay master in production mode.
kind: ReplicationController
apiVersion: v1
metadata: 
  name: docker-relay-master-controller-v1
  namespace: default
  labels: 
    k8s-app: docker-relay
    version: v1
spec: 
  replicas: 1
  selector: 
    k8s-app: docker-relay
    docker-relay-mode: master
    version: v1
  template: 
    metadata: 
      labels: 
        k8s-app: docker-relay
        docker-relay-mode: master
        version: v1
    spec: 
      containers: 
        - 
          name: docker-relay
          image: kubernetes/docker-relay:latest
          imagePullPolicy: IfNotPresent
          ports: 
            - 
              name: docker-relay
              containerPort: 5555
              hostPort: 5555
              protocol: TCP
          env: 
            - 
              name: DOCKER_RELAY_MODE
              value: master
          command:
            - "python"
            - "./docker_relay.py"
            - "--debug"
