apiVersion: v1
kind: Service
metadata: 
  name: docker-relay
  namespace: default
  labels: 
    k8s-app: docker-relay
    kubernetes.io/name: DockerRelay
    version: v1
spec: 
  selector: 
    docker-relay-mode: master
  ports: 
    - 
      name: docker-relay
      port: 5555
      targetPort: docker-relay
      protocol: TCP
